"""CubeLoop — Pythonic async-native agent framework."""

from importlib.metadata import PackageNotFoundError, version as _pkg_version

try:
    __version__ = _pkg_version("cubeloop")
except PackageNotFoundError:  # pragma: no cover — non-installed checkout
    __version__ = "0.0.0+unknown"


from cubeloop.agent import (
    Agent,
    AgentState,
    AgentTool,
    AgentToolResult,
    run_agent_loop,
    run_agent_loop_continue,
    tool,
)
from cubeloop.middleware import Middleware, compose_middleware
from cubeloop.providers import (
    AssistantMessage,
    BaseProvider,
    BoundModel,
    DEFAULT_TRIGGER_ERRORS,
    FallbackBoundModel,
    Message,
    MessageStream,
    Model,
    Provider,
    ReasoningControl,
    ReasoningEffort,
    ReasoningMode,
    ReasoningSummary,
    StreamEvent,
    StreamOptions,
    TextContent,
    ToolCall,
    ToolDefinition,
    ToolResultMessage,
    UserMessage,
    is_synthetic_message,
    synthetic_user_message,
)
from cubeloop.errors import (
    ContentFiltered,
    ContextLengthExceeded,
    ModelNotFound,
    ProviderAuthFailed,
    ProviderBadRequest,
    ProviderError,
    ProviderUnavailable,
    RateLimited,
)
from cubeloop.providers.capability import (
    CapabilityDescriptor,
    CapabilityWarning,
    PayloadPreview,
    ReasoningCapability,
    TemperatureSpec,
    apply_reasoning_control,
    lint_capability,
    preview_payload,
)
from cubeloop.providers.images import (
    AssistantImages,
    BaseImagesProvider,
    ImagesAborted,
    ImagesCapabilityDescriptor,
    ImagesContext,
    ImagesCost,
    ImagesModel,
    ImagesOptions,
    ImagesProvider,
    SizeSpec,
)
from cubeloop.types import JsonObject, JsonValue, StructuredObject, StructuredValue
from cubeloop.session import (
    ContinueExecutionRequest,
    DeliveryError,
    ExecutionBusy,
    ExecutionError,
    ExecutionEventEnvelope,
    ExecutionFinished,
    ExecutionRequest,
    ExecutionResult,
    ExecutionSession,
    InputCommitted,
    InputEnvelope,
    InputReceipt,
    MessageView,
    PromptExecutionRequest,
    RespondExecutionRequest,
    ToolExecutionBinding,
    TurnExecutionContext,
)

__all__ = [
    "__version__",
    "Agent",
    "AgentState",
    "AgentTool",
    "AgentToolResult",
    "AssistantImages",
    "AssistantMessage",
    "BaseImagesProvider",
    "BaseProvider",
    "BoundModel",
    "CapabilityDescriptor",
    "ContentFiltered",
    "ContinueExecutionRequest",
    "DeliveryError",
    "ContextLengthExceeded",
    "DEFAULT_TRIGGER_ERRORS",
    "FallbackBoundModel",
    "ExecutionBusy",
    "ExecutionError",
    "ExecutionEventEnvelope",
    "ExecutionFinished",
    "ExecutionRequest",
    "ExecutionResult",
    "ExecutionSession",
    "ImagesAborted",
    "ImagesCapabilityDescriptor",
    "ImagesContext",
    "ImagesCost",
    "ImagesModel",
    "ImagesOptions",
    "ImagesProvider",
    "InputCommitted",
    "InputEnvelope",
    "InputReceipt",
    "JsonObject",
    "JsonValue",
    "Message",
    "MessageStream",
    "MessageView",
    "Middleware",
    "Model",
    "ModelNotFound",
    "Provider",
    "PromptExecutionRequest",
    "ProviderAuthFailed",
    "ProviderBadRequest",
    "ProviderError",
    "ProviderUnavailable",
    "RateLimited",
    "ReasoningCapability",
    "ReasoningControl",
    "ReasoningEffort",
    "ReasoningMode",
    "ReasoningSummary",
    "RespondExecutionRequest",
    "SizeSpec",
    "StreamEvent",
    "StreamOptions",
    "StructuredObject",
    "StructuredValue",
    "TemperatureSpec",
    "TextContent",
    "ToolCall",
    "ToolDefinition",
    "ToolExecutionBinding",
    "ToolResultMessage",
    "TurnExecutionContext",
    "UserMessage",
    "CapabilityWarning",
    "PayloadPreview",
    "apply_reasoning_control",
    "is_synthetic_message",
    "lint_capability",
    "preview_payload",
    "synthetic_user_message",
    "compose_middleware",
    "run_agent_loop",
    "run_agent_loop_continue",
    "tool",
]
